### PR TITLE
More sensible TerminalFinderButton

### PR DESCRIPTION
**Pull request by ashfinal**
Reuse current tab of current window instead of always opening new window;
You can change PWD by selecting certain folder as well, `.app`, `.Workflow` files are also supported;
Determine busy terminal window (vim, wget, etc) to open new window; 
Use persist storage to show first-time launching greeting, update notification, and other staff.

### CODE REVIEW

**Comment by lexrus** [comment]
Awesome refinements. But I'm not familiar with Apple Script.

**Comment by ashfinal** [comment]
@lexrus I wrote some AppleScript before, but never really dug into it. After doing some Google search and write-run-modify loop, the shinny TerminalButton was out! 
I've used this button for a few days, it worked as intended, as far as I know.
Also, the script was well documented, in case you want to check it out. :)

**Comment by lexrus** [comment]
@ashfinal I respect what you did. But I prefer writing scripts in JavaScript for some reasons. Please keep your fork, I'll add a link in my README.md.

**Comment by ashfinal** [comment]
OK, I would keep the fork.
I just realize that this script may be a little long (and grisly), which could be less short.

**Pull request closed without merging**
